# Generated by Django 3.1.7 on 2021-03-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210326_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upc',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
